Models/Evento.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROJETO3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Evento
    {
        public Evento()
        {
            this.MasterEventos = new HashSet<MasterEventos>();
            this.Grupo = new HashSet<Grupo>();
            this.QuestaoEvento = new HashSet<QuestaoEvento>();
            this.Assunto = new HashSet<Assunto>();
        }
    
        public int codEvento { get; set; }
        public string descricao { get; set; }
        public System.DateTime data { get; set; }
        public byte codTipoEvento { get; set; }
        public string codStatus { get; set; }
        public short codProfessor { get; set; }
        public string identificador { get; set; }
    
        public virtual ICollection<MasterEventos> MasterEventos { get; set; }
        public virtual Status Status { get; set; }
        public virtual TipoEvento TipoEvento { get; set; }
        public virtual Professor Professor { get; set; }
        public virtual ICollection<Grupo> Grupo { get; set; }
        public virtual ICollection<QuestaoEvento> QuestaoEvento { get; set; }
        public virtual ICollection<Assunto> Assunto { get; set; }
    }
}

Models/EventoViewModel.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace PROJETO3.Models
{
    [NotMapped]
    public class EventoViewModel
    {
        [Key]
        public int codEvento { get; set; }
        [Required(ErrorMessage = "É necessário a Descrição do evento")]
        public string descricao { get; set; }
        [Required(ErrorMessage = "Insira uma DATA Válida")]
        public System.DateTime data { get; set; }
        [Required(ErrorMessage = "Escolha um Tipo de Evento")]
        public byte codTipoEvento { get; set; }
        [Required]
        public string codStatus { get; set; }
        [Required]
        public short codProfessor { get; set; }
        [Required(ErrorMessage = "É preciso gerar uma chave identificadora para o novo evento!")]
        public string identificador { get; set; }
        [Required(ErrorMessage = "Esse evento precisa estar associado a um Assunto")]
        public int codAssunto { get; set; }


        //   PARA SER IMPLEMENTADO NA CONTROLLER:

        /*
            String x="";           
            
            while (x.Length < 8)
            {

                char c = (char) sorteio (0,127);
                if (c > 50 && c < 57 || c > 97 && c < 120)
                {
                    x = x + c;
                }

                 http://www.ascii-code.com

            } */



    }
}

Controllers/EventoController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PROJETO3.Models;
using System.Text;

namespace PROJETO3.Controllers
{
    public class EventoController : Controller
    {
        private Entidades db = new Entidades();

        // GET: /Evento/
        public ActionResult Index()
        {            
                var evento = db.Evento.Include(e => e.TipoEvento).Include(e => e.Professor).Include(e => e.Assunto);
                return View(evento.ToList());
        }

        // GET: /Evento/Create
        public ActionResult Cadastrar()
        {
            List<TipoEvento> tipoevento = new List<TipoEvento>();
            SelectList tipoeventoList = new SelectList(tipoevento, "ID", "Name");
            ViewBag.TipoEvento = tipoeventoList;
            return View();

            ViewBag.TipoEvento = new SelectList(db.TipoEvento, "codTipoEvento", "descTipoEvento");
            ViewBag.Professor = new SelectList(db.Professor, "codProfessor", "nome");
            return View();
        }

        // POST: /Evento/Cadastrar
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.

        /*
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Cadastrar(EventoViewModel evento)
        {
            try
            {
                evento.ativo = true;
                StringBuilder sb = new StringBuilder();
                sb.AppendFormat("INSERT INTO Evento VALUES ('{0}', {1}, '{2}', HASHBYTES('SHA1', '{3}'), {4})",
                    evento.nmEvento,
                    evento.codCurso,
                    evento.email,
                    evento.senha,
                    1);
                using (var ctx = new Entidades())
                {
                    ctx.Database.ExecuteSqlCommand(sb.ToString());
                    ctx.SaveChanges();
                    ViewBag.OK = "S";
                }
            }
            catch (Exception)
            {
                ViewBag.OK = "N";
            }
            return View("Resultado", evento);  
    }
    
        // GET: /Evento/Editar/5
        public ActionResult Editar(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Evento evento = db.Evento.Find(id);
            if (evento == null)
            {
                return HttpNotFound();
            }
            ViewBag.codCurso = new SelectList(db.Curso, "codCurso", "nmCurso", evento.codCurso);
            return View(evento);
        }

        // POST: /Evento/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Editar([Bind(Include = "codEvento,nmEvento,codCurso,email,senha,ativo")] Evento evento)
        {
            if (ModelState.IsValid)
            {
                db.Entry(evento).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.codCurso = new SelectList(db.Curso, "codCurso", "nmCurso", evento.codCurso);
            return View(evento);
        }

        // GET: /Evento/Deletar/5
        public ActionResult Deletar(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Evento evento = db.Evento.Find(id);
            if (evento == null)
            {
                return HttpNotFound();
            }
            return View(evento);
        }

        // POST: /Evento/Deletar/5
        [HttpPost, ActionName("Deletar")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Evento evento = db.Evento.Find(id);
            db.Evento.Remove(evento);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        
        // REMOTE DA VALIDAÇÃO DO EMAIL
        public JsonResult VerificarEmail(string email) {
            int intCont = 0;
            intCont=db.Evento.Where(m => m.email == email).Count();
            if (intCont > 0)
                return Json("E-Mail Já Cadrastrado",JsonRequestBehavior.AllowGet);
            return Json(true, JsonRequestBehavior.AllowGet);
        }

        */

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Evento/Cadastrar.cshtml
@model PROJETO3.Models.EventoViewModel

@{
    ViewBag.Title = "Cadastro de Novo Evento";
}

<h2>@ViewBag.Title</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Evento</h4>
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.descricao, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.descricao)
                @Html.ValidationMessageFor(model => model.descricao)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.data, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.data)
                @Html.ValidationMessageFor(model => model.data)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.codTipoEvento, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("TipoEvento")
                @*Html.DropDownListFor(model => model.codTipoEvento, null, "Defina o Tipo de Evento")*@
                @Html.ValidationMessageFor(model => model.codTipoEvento)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.codStatus, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.codStatus)
                @Html.ValidationMessageFor(model => model.codStatus)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.identificador, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.identificador)
                @Html.ValidationMessageFor(model => model.identificador)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.codAssunto, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.codAssunto, null, "Assunto associado ao evento")
                @Html.ValidationMessageFor(model => model.codAssunto)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Cadastrar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Evento/Index.cshtml
@model IEnumerable<PROJETO3.Models.Evento>

    @{
        ViewBag.Title = "Eventos Disponíveis";
    }

    <h2>@ViewBag.Title</h2>

<p>
    @Html.ActionLink("Cadastrar Evento", "Cadastrar", "Evento", null, new { @class = "btn btn-primary btn-large" })
</p>

@{
    if (Model.Count() > 0)
    {
        var grid = new WebGrid(canPage: true, rowsPerPage: 10, canSort: true, ajaxUpdateContainerId: "gridPart");
        grid.Bind(Model, rowCount: Model.ToList().Count(), autoSortAndPage: true);
        grid.Pager(mode: WebGridPagerModes.All,
            firstText: "<< Primeiro", lastText: "Último >>",
            previousText: "< Anterior", nextText: "Próximo >",
            numericLinksCount: 10);

        @grid.GetHtml(htmlAttributes: new { id = "gridPart" },
          tableStyle: "table table-bordered table-hover",
          headerStyle: "webgrid-header",
          footerStyle: "webgrid-footer text-center",
          alternatingRowStyle: "webgrid-alternating-row",
          selectedRowStyle: "webgrid-selected-row",
          rowStyle: "webgrid-row-style",
          displayHeader: true,
          columns: grid.Columns(


         grid.Column(columnName: "identificador", header: "Identificador", format: null, style: "Destaque", canSort: true),
         grid.Column(columnName: "descricao", header: "Descrição", format: null, style: "Destaque", canSort: true),
         grid.Column(columnName: "data", header: "Data", format: null, style: "Destaque", canSort: true),
         grid.Column(columnName: "Professor.nome", header: "Nome Professor", format: null, style: null, canSort: true),
         grid.Column(columnName: "Status.descStatus", header: "Status", format: null, style: "Destaque", canSort: true)


         ));
    }
    else
    {
        <p class="alert-danger">Não há registros para a pesquisa selecionada.</p>
    }
}